host: localhost
info:
  description: |-
    The purpose of this application is to provide an application
    that is using plain go code to define an API

    This should demonstrate all the possible comment annotations
    that are available to turn go code into a fully compliant swagger 2.0 spec
  title: Member system API.
  version: 0.0.1
paths: {}
schemes:
- http
swagger: "2.0"
