// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	entities "GoCleanArchitecture/entities"

	mock "github.com/stretchr/testify/mock"
)

// TokenRepository is an autogenerated mock type for the TokenRepository type
type TokenRepository struct {
	mock.Mock
}

// CheckRefreshToken provides a mock function with given fields: id, refreshToken
func (_m *TokenRepository) CheckRefreshToken(id string, refreshToken string) (entities.User, error) {
	ret := _m.Called(id, refreshToken)

	var r0 entities.User
	if rf, ok := ret.Get(0).(func(string, string) entities.User); ok {
		r0 = rf(id, refreshToken)
	} else {
		r0 = ret.Get(0).(entities.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(id, refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateRefreshToken provides a mock function with given fields: id, refreshToken
func (_m *TokenRepository) UpdateRefreshToken(id string, refreshToken string) error {
	ret := _m.Called(id, refreshToken)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(id, refreshToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
